
INSERT INTO `users`(`NAME`, `PASSWORD`, `DATE_REGISTERES`) VALUES ('Boryana Yordanova','boryana','2016-02-17 00:00:00');
INSERT INTO `users`(`NAME`, `PASSWORD`, `DATE_REGISTERES`) VALUES ('Iskren Yordanova','iskren','2016-03-17 00:00:00');
INSERT INTO `users`(`NAME`, `PASSWORD`, `DATE_REGISTERES`) VALUES ('Dimitar Conev','dimitar','2016-02-22 00:00:00');
INSERT INTO `users`(`NAME`, `PASSWORD`, `DATE_REGISTERES`) VALUES ('Anton Lyapov','anton','2016-04-15 00:00:00');




INSERT INTO `coordinates`(`USER_ID`, `REC_DATE`, `COOR_X`, `COOR_Y`) VALUES (3, '2016-04-15 00:00:00', 25, 25);
INSERT INTO `coordinates`(`USER_ID`, `REC_DATE`, `COOR_X`, `COOR_Y`) VALUES (3, '2016-04-15 00:10:00', 26, 26);
INSERT INTO `coordinates`(`USER_ID`, `REC_DATE`, `COOR_X`, `COOR_Y`) VALUES (3, '2016-04-15 00:20:00', 27, 28);
INSERT INTO `coordinates`(`USER_ID`, `REC_DATE`, `COOR_X`, `COOR_Y`) VALUES (3, '2016-04-16 00:10:00', 28, 28);
INSERT INTO `coordinates`(`USER_ID`, `REC_DATE`, `COOR_X`, `COOR_Y`) VALUES (3, '2016-04-16 00:20:00', 29, 30);
INSERT INTO `coordinates`(`USER_ID`, `REC_DATE`, `COOR_X`, `COOR_Y`) VALUES (3, '2016-04-16 00:30:00', 31, 32);







SELECT 
CASE 
	WHEN USER_ID_ONE <> 3 THEN USER_ID_ONE
    ELSE USER_ID_TWO
    END AS USER_ID_FRIEND
FROM RELATIONS
WHERE (USER_ID_ONE = 3 OR USER_ID_TWO = 3) AND REQUEST_STATUS = 1





-- GET ALL USERS NOT MY FRIENDS
SELECT ID, NAME FROM USERS 
WHERE ID NOT IN (SELECT 
                    CASE 
                        WHEN USER_ID_ONE <> 3 THEN USER_ID_ONE
                        ELSE USER_ID_TWO
                        END AS USER_ID_FRIEND
                    FROM RELATIONS
                    WHERE (USER_ID_ONE = 3 OR USER_ID_TWO = 3) AND REQUEST_STATUS = 1)
	AND ID <> 3
    AND LOWER(NAME) LIKE '%y%'
    order by 2                        




    -- GET FREIND REQUEST_STATUS
    SELECT USER_ID_ONE, NAME FROM RELATIONS LEFT OUTER JOIN USERS ON RELATIONS.USER_ID_ONE = USERS.ID WHERE USER_ID_TWO = 5 AND REQUEST_STATUS = 0




    SELECT * FROM 
(SELECT CASE WHEN USER_ID_ONE <> 4 THEN USER_ID_ONE ELSE USER_ID_TWO END AS FRIEND_ID, * FROM RELATIONS WHERE (USER_ID_ONE = 4 OR USER_ID_TWO = 4) AND REQUEST_STATUS = 1) FRIENDS
LEFT OUTER JOIN USERS ON FRIENDS.FRIENDS_ID = USERS.ID


SELECT DISTINCT USERS.ID, USERS.NAME, COORDINATES.COOR_X, COORDINATES.COOR_Y, COORDINATES.REC_DATE FROM 
(SELECT CASE WHEN USER_ID_ONE <> 4 THEN USER_ID_ONE ELSE USER_ID_TWO END AS FRIEND_ID FROM RELATIONS WHERE (USER_ID_ONE = 4 OR USER_ID_TWO = 4) AND REQUEST_STATUS = 1) FRIENDS
LEFT OUTER JOIN USERS ON FRIENDS.FRIEND_ID = USERS.ID
LEFT OUTER JOIN (SELECT USER_ID, MAX(REC_DATE) AS MAX_REC_DATE FROM COORDINATES GROUP BY USER_ID) MAX_DATE ON FRIENDS.FRIEND_ID = MAX_DATE.USER_ID
LEFT OUTER JOIN COORDINATES ON FRIENDS.FRIEND_ID = COORDINATES.USER_ID AND COORDINATES.REC_DATE = MAX_DATE.MAX_REC_DATE

3
Boryana Yordanova
25.000000
25.000000
2016-05-12 00:20:00